version: '3.8'

services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    env_file:
      - .env
    ports:
      - 5432:5432
